using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public abstract class TeamBlastOrder : BaseCharacter
{
    //Note: Team Sonic's main team blast ultimate attack while in Super Form, When performing Sonic Overdrive, Knuckles grabs onto Tails by his feet, who is also holding on to Sonic's feet, and begins swinging them around to gain momentum. After spinning a few times, Knuckles lets go of Tails who then kicks Sonic into the air while Sonic is surrounded by a red aura. Sonic yells "Blast Away!" and unleashes a massive Light Speed Attack, causing him to zoom around in the air at astounding speeds while striking enemies for about two seconds before landing on the ground again.

    //To perform Sonic Overdrive in gameplay, the player must press the White Button/R1ps3.png/Gamecube Z Button.png when the Team Blast Gauge is full. When performing this technique, it destroys all normal enemies in the vicinity, and also inflicts a large amount of damage to bosses. Additionally, while the Team Blast Gauge is resetting from the usage of Sonic Overdrive, the player can use the Light Speed Attack to make Sonic destroy any additional enemies by jumping and pressing the action button (XboxX.png/PSSquareButton.png/SNNBGAMECUBEDISCO.png) when Team Sonic is in Speed Formation. Alternatively, if the player uses the Thunder Shoot or Fire Dunk while the Team Blast Gauge is resetting, Sonic will perform the Light Speed Attack automatically.

    //When performing Chaos Inferno, Shadow grabs the green Chaos Emerald and invokes Chaos Control to freeze time while Rouge lifts Omega up into the air by his head. Omega then reconfigures his arms into laser cannons and fires giant purple laser beams from each of them while rotating his torso counter-clockwise, blasting everything within range.

    //Note: Team Dark's main team blast ultimate attack To perform Chaos Inferno in gameplay, the player must press the White Button/R1ps3.png/Gamecube Z Button.png when the Team Blast Gauge is full.When performing this technique, it destroys all normal enemies in the vicinity, and also inflicts a large amount of damage to bosses.Additionally, while the Team Blast Gauge is resetting from the usage of Chaos Inferno, time is completely stopped, meaning that enemies, doors, switches and even the stage time are frozen in place.Any damage that enemies sustain will take effect once time unfreezes.While this effect is useful for getting a good time in Stages and attacking enemies, it also means the environment in the Stages will not react to some of the player's actions before time unfreezes. However, the player can instantly reset the Team Blast Gauge early (and manually unfreeze time in the process) by pressing the White Button/R1ps3.png/Gamecube Z Button.png again.

    //Note: Team Rose's main team blast ulimate attack When performing Flower Festival, Big bounces Amy and Cream (who are curled into balls) around on the top of his umbrella while he is twirling it. Big then quickly lifts up his umbrella, throwing Amy and Cream slightly up into the air. After that, Amy lands and balances on top of Big's umbrella while joining hands with Cream so that Cream stands upside-down, and the two strike a pose while Big lifts up his umbrella and dances as high as possible and strikes a pose as well. As Cheese then circles around them, the group releases an explosion of flowers at their enemies.

    //To perform Flower Festival in gameplay, the player must press the White Button/R1ps3.png/Gamecube Z Button.png when the Team Blast Gauge is full.When performing this technique, it destroys all normal enemies in the vicinity, and also inflicts a large amount of damage to bosses.Additionally, when activated, Team Rose is granted Invincible, a Barrier and a red, blue and yellow Power Core.Compared to other Team Blasts, Flower Festival has a large attack radius.Also, in battles against other playable teams, the opposing team cannot switch to another team formation for a short time after Flower Festival is used, with flowers appearing above the affected characters until it wears off.

    //Note: Team Chaotix's main team blast ulimate attack When performing Chaotix Recital, Espio strums a shamisen while Charmy beats on a drum. While his teammates are playing their instruments, Vector then "sings" into a microphone and the three of them together release loud sounds in all directions at their foes. While playing, an audience can be heard cheering for them.

    //To perform Chaotix Recital in gameplay, the player must press the White Button/R1ps3.png/Gamecube Z Button.png when the Team Blast Gauge is full.When performing this technique, it destroys all normal enemies in the vicinity, and also inflicts a large amount of damage to bosses.During the attack, the player receives a Rings Item Box for each enemy destroyed, with each Item Box containing a random number of Rings.Additionally, while the Team Blast Gauge is resetting from the usage of Chaotix Recital, the player receives a Rings Item Box holding a random number of Rings for every enemy destroyed.

    //Note: Team Super Sonic's main team blast ulimate attack When performing Super Sonic Power, Super Sonic, Super Tails and Super Knuckles fly up and start charging their powers, the emblems representing the Speed type, Fly type and Power type appearing behind the respective user in the background. Once fully charged, Super Sonic, Super Tails and Super Knuckles deliver a rapid barrage of exceedingly powerful semi-Homing Attacks, similar to the Light Speed Attack, on their target.

    //Super Sonic Power is the only attack in Team Sonic's arsenal capable of dealing damage to Metal Overlord. To perform it in gameplay, the player must press the White Button/R1ps3.png/Gamecube Z Button.png when the Team Blast Gauge is full. This move must be used a total of five times to defeat Metal Overlord.

}
